### PR TITLE
fix: avoid registering disposables repeatedly (#48)

### LINKED ISSUE #48: [bug] Repeated items in tooltip
I think I found a bug. When hovering a line that has a tour marker, the tooltip displays the same item several times.

tooltip_error

The number is not constant, but ~I haven't found a correlation with the number of steps or step comments~.

~Edit: the number of tooltip items does indeed go up with the number of steps. My guess is that "repeated" steps retrieved by the following function are not correctly filtered here:
https://github.com/vsls-contrib/codetour/blob/1808b3e06c550635a86b733dda42d265832afdb5/src/decorator.ts#L16~

Edit 2: actually, it seems like the whole **hover provider** is being registered again every time I edit the tour.

### PR DESCRIPTION
**Pull request by alvaromartmart**
I think this fixes #48.

`disposables` were only being `dispose()`'d when showMarkers was false, but were otherwise being added to the decorators every time showMarkers was evaluated true. This caused the hover providers to be registered several times... and potentially causing other issues that I have not investigated (that `onDidChangeActiveTextEditor` decorator there)

### CODE REVIEW

File: src/decorator.ts [hunk 1]
```diff
@@ -88,6 +88,11 @@ export async function registerDecorators() {
     ],
     () => {
       const activeEditor = vscode.window.activeTextEditor;
+      if (activeEditor) {
+        activeEditor.setDecorations(TOUR_DECORATOR, []);
+        disposables.forEach(disposable => disposable.dispose());
```
Comment (lostintangent) [inline src/decorator.ts:93]: We probably only need to do this when the user turns off the markers. For the sake of fixing this bug, we might be able to just get away with clearing the decorations each time we render new ones?

File: src/decorator.ts [hunk 2]
```diff
@@ -88,6 +88,11 @@ export async function registerDecorators() {
     ],
     () => {
       const activeEditor = vscode.window.activeTextEditor;
+      if (activeEditor) {
```
Comment (lostintangent) [inline src/decorator.ts:91]: I wonder if we shouldn't split this into two `reaction` calls: one that enables/disables the markers, and one that updates the markers based on new tours/steps being added.

Comment (alvaromartmart) [reply src/decorator.ts:91]: I'm not familiar with how `reaction` works but I think I know what you mean. This code seems to be triggered by two different events, right?
* Toggling the markers
* Updating the tour(s)
In that case yes, I guess it may be *cleaner* split it into two different flows:
* Tours change -> update the decorators that need to be available.
* Markers show/hide -> set / dispose the decorators.

Comment (alvaromartmart) [reply src/decorator.ts:91]: But wait, updating the decorators should also add/dispose them, so maybe it does make sense to "merge" both events so we react to both changes

File: src/decorator.ts [hunk 3]
```diff
@@ -88,13 +89,12 @@ export async function registerDecorators() {
...
-        disposables.forEach(disposable => disposable.dispose());
-        disposables = [];
-      }
+
       if (store.showMarkers) {
-        disposables.push(registerHoverProvider());
+        if (hoverProviderDisposable === undefined) {
+          hoverProviderDisposable = registerHoverProvider();
+          disposables.push(hoverProviderDisposable);
+        }
```
Comment (alvaromartmart) [inline src/decorator.ts:97]: How about this? We keep track of the `HoverProvider` disposable and make sure we only register it once, which solves the orginal issue

**Comment by lostintangent** [comment]
Thanks so much!

**Comment by alvaromartmart** [comment]
Happy to help!
